SELECT CONVERT(CHAR(24),
       CONVERT(VARBINARY(4), DATEDIFF(SECOND,'1970-01-01 00:00:00', GETUTCDATE())) +
       CONVERT(VARBINARY(6), RAND()) + 
	   CONVERT(VARBINARY(2), @@SPID ^ @@CPU_BUSY ^ @@IDLE), 2)